//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuisBot.Messages.CardMessagesResource", typeof(CardMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi.
        /// </summary>
        internal static string CarouselListButtonTitle {
            get {
                return ResourceManager.GetString("CarouselListButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non mi interessano.
        /// </summary>
        internal static string CarouselListFinalElementButtonTitle {
            get {
                return ResourceManager.GetString("CarouselListFinalElementButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non mi interessano.
        /// </summary>
        internal static string CarouselListFinalElementButtonValue {
            get {
                return ResourceManager.GetString("CarouselListFinalElementButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non desideri aggiungere altro?.
        /// </summary>
        internal static string CarouselListFinalElementTitle {
            get {
                return ResourceManager.GetString("CarouselListFinalElementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crea nuova lista.
        /// </summary>
        internal static string GreetingCardNewListPayload {
            get {
                return ResourceManager.GetString("GreetingCardNewListPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea nuova lista.
        /// </summary>
        internal static string GreetingCardNewListTitle {
            get {
                return ResourceManager.GetString("GreetingCardNewListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apri ultima lista.
        /// </summary>
        internal static string GreetingCardOldListPayload {
            get {
                return ResourceManager.GetString("GreetingCardOldListPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usa l&apos;ultima lista.
        /// </summary>
        internal static string GreetingCardOldListTitle {
            get {
                return ResourceManager.GetString("GreetingCardOldListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dammi gli orari.
        /// </summary>
        internal static string GreetingCardTimeTablePayload {
            get {
                return ResourceManager.GetString("GreetingCardTimeTablePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orari di apertura.
        /// </summary>
        internal static string GreetingCardTimeTableTitle {
            get {
                return ResourceManager.GetString("GreetingCardTimeTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vedi promo.
        /// </summary>
        internal static string GreetingCardViewPromoPayload {
            get {
                return ResourceManager.GetString("GreetingCardViewPromoPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedi promozioni.
        /// </summary>
        internal static string GreetingCardViewPromoTitle {
            get {
                return ResourceManager.GetString("GreetingCardViewPromoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi.
        /// </summary>
        internal static string ListCardButtonTitle {
            get {
                return ResourceManager.GetString("ListCardButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non mi interessano.
        /// </summary>
        internal static string ListCardFinalButtonPayload {
            get {
                return ResourceManager.GetString("ListCardFinalButtonPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non mi interessano.
        /// </summary>
        internal static string ListCardFinalButtonTitle {
            get {
                return ResourceManager.GetString("ListCardFinalButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grazie.
        /// </summary>
        internal static string YesOrNoCardNoPayload {
            get {
                return ResourceManager.GetString("YesOrNoCardNoPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grazie.
        /// </summary>
        internal static string YesOrNoCardNoTitle {
            get {
                return ResourceManager.GetString("YesOrNoCardNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sì grazie.
        /// </summary>
        internal static string YesOrNoCardYesPayload {
            get {
                return ResourceManager.GetString("YesOrNoCardYesPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sì grazie.
        /// </summary>
        internal static string YesOrNoCardYesTitle {
            get {
                return ResourceManager.GetString("YesOrNoCardYesTitle", resourceCulture);
            }
        }
    }
}
