//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuisBot.Messages.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrivi l&apos;elenco dei prodotti che vuoi aggiungere, per esempio: vino, birra, pasta.
        /// </summary>
        internal static string AddOtherProducts {
            get {
                return ResourceManager.GetString("AddOtherProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotti aggiunti con successo.
        /// </summary>
        internal static string AskIfContinueToAddProduct {
            get {
                return ResourceManager.GetString("AskIfContinueToAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi aggiungere altri prodotti alla lista?.
        /// </summary>
        internal static string AskIfWantAddProduct {
            get {
                return ResourceManager.GetString("AskIfWantAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuoi vedere la posizione dei prodotti nel supermercato?.
        /// </summary>
        internal static string AskIfWantSeePosition {
            get {
                return ResourceManager.GetString("AskIfWantSeePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhm... forse manca qualcosa. Vuoi un consiglio?.
        /// </summary>
        internal static string AskIfWantSuggestions {
            get {
                return ResourceManager.GetString("AskIfWantSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli dove salvare il prodotto selezionato:.
        /// </summary>
        internal static string AskWhatListUse {
            get {
                return ResourceManager.GetString("AskWhatListUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrivi l&apos;elenco dei prodotti che vuoi aggiungere, per esempio: vino, birra, pasta.
        /// </summary>
        internal static string AskWhatToAdd {
            get {
                return ResourceManager.GetString("AskWhatToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare categoria dei prodotti in promo:.
        /// </summary>
        internal static string CategoriesListCardTitle {
            get {
                return ResourceManager.GetString("CategoriesListCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Categoria non disponibile... Riprova:.
        /// </summary>
        internal static string CourtesyCategoryError {
            get {
                return ResourceManager.GetString("CourtesyCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! La scelta è non valida... Riprova:.
        /// </summary>
        internal static string CourtesyChooseError {
            get {
                return ResourceManager.GetString("CourtesyChooseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Qualcosa è andato storto....
        /// </summary>
        internal static string CourtesyError {
            get {
                return ResourceManager.GetString("CourtesyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Prodotto non valido... Riprova:.
        /// </summary>
        internal static string CourtesyProductError {
            get {
                return ResourceManager.GetString("CourtesyProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfetto! Ho creato una nuova lista..
        /// </summary>
        internal static string CreatedList {
            get {
                return ResourceManager.GetString("CreatedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tua ultima lista della spesa era vuota, ne ho creata una nuova!.
        /// </summary>
        internal static string EmptyShoppingList {
            get {
                return ResourceManager.GetString("EmptyShoppingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi spiace ma non riesco a capire... Provo ad aiutarti:.
        /// </summary>
        internal static string ErrorLimitExceeded {
            get {
                return ResourceManager.GetString("ErrorLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao {0}, cosa vuoi fare?.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosa posso fare per te?.
        /// </summary>
        internal static string GreetingVariant {
            get {
                return ResourceManager.GetString("GreetingVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi dispiace, ma al momento gli orari di apertura non sono disponibili.
        /// </summary>
        internal static string NoOpeningHours {
            get {
                return ResourceManager.GetString("NoOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi dispiace ma non ci sono prodotti in promozione correlati alla tua spesa.
        /// </summary>
        internal static string NoPromoProduct {
            get {
                return ResourceManager.GetString("NoPromoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi dispiace ma non sono presenti prodotti in promozione per questa categoria....
        /// </summary>
        internal static string NoPromoProductForCategorySelected {
            get {
                return ResourceManager.GetString("NoPromoProductForCategorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi dispiace ma al momento non vi sono prodotti suggeriti per te.
        /// </summary>
        internal static string NoSuggestionProduct {
            get {
                return ResourceManager.GetString("NoSuggestionProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scusa, non ho capito..
        /// </summary>
        internal static string NotUnderstoodRequest {
            get {
                return ResourceManager.GetString("NotUnderstoodRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotto aggiunto con successo..
        /// </summary>
        internal static string ProductAdded {
            get {
                return ResourceManager.GetString("ProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ti segnaliamo che ci sono anche questi prodotti in promozione che potrebbero interessarti:.
        /// </summary>
        internal static string PromoProducts {
            get {
                return ResourceManager.GetString("PromoProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un altra categoria:.
        /// </summary>
        internal static string SelectAnotherCategory {
            get {
                return ResourceManager.GetString("SelectAnotherCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selezionare un altra opzione:.
        /// </summary>
        internal static string SelectAnotherOption {
            get {
                return ResourceManager.GetString("SelectAnotherOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Che ne dici di..?.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ti segnaliamo che ci sono anche questi prodotti in promozione che potrebbero interessarti:.
        /// </summary>
        internal static string SelectPromoProduct {
            get {
                return ResourceManager.GetString("SelectPromoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eccoti alcuni prodotti in promozione in questa categoria:.
        /// </summary>
        internal static string SelectPromoProductByCategory {
            get {
                return ResourceManager.GetString("SelectPromoProductByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prossime aperture straordinare:.
        /// </summary>
        internal static string ShowExtraOpeningHours {
            get {
                return ResourceManager.GetString("ShowExtraOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gli orari del negozio sono i seguenti:.
        /// </summary>
        internal static string ShowOpeningHours {
            get {
                return ResourceManager.GetString("ShowOpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riepilogo lista spesa:.
        /// </summary>
        internal static string ShowShoppingListReview {
            get {
                return ResourceManager.GetString("ShowShoppingListReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciao.
        /// </summary>
        internal static string StartGreetings {
            get {
                return ResourceManager.GetString("StartGreetings", resourceCulture);
            }
        }
    }
}
